location: .gitman
sources:
  - repo: https://github.com/pairs-lab/pairs_multirotor_simulator
    name: pairs_multirotor_simulator
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_multirotor_simulator
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_uav_state_estimators.git
    name: pairs_uav_state_estimators
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_state_estimators
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_uav_hw_api.git
    name: pairs_uav_hw_api
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_hw_api
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_lib.git
    name: pairs_lib
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_lib
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_msgs.git
    name: pairs_msgs
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_uav_controllers.git
    name: pairs_uav_controllers
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_uav_managers.git
    name: pairs_uav_managers
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_uav_trackers.git
    name: pairs_uav_trackers
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_uav_autostart.git
    name: pairs_uav_autostart
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_autostart
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_uav_testing.git
    name: pairs_uav_testing
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_uav_trajectory_generation.git
    name: pairs_uav_trajectory_generation
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/pairs-lab/pairs_uav_status.git
    name: pairs_uav_status
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_status
    scripts:
      - git submodule update --init --recursive
