<?xml version="1.0"?>
<package format="2">

  <name>pairs_uav_core</name>
  <version>1.0.0</version>
  <description>The PAIRS UAV Core metapackage</description>

  <maintainer email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</maintainer>
  <author email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</author>

  <license>BSD 3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>cmake_modules</depend>
  <depend>rospy</depend>

  <depend version_gte="1.16.666">rosbag</depend>
  <depend version_gte="0.7.666">tf2_ros</depend>
  <depend version_gte="0.7.666">tf2</depend>

  <depend>pairs_msgs</depend>
  <depend>pairs_lib</depend>
  <depend>pairs_uav_hw_api</depend>
  <depend>pairs_uav_managers</depend>
  <depend>pairs_uav_controllers</depend>
  <depend>pairs_uav_trackers</depend>
  <depend>pairs_uav_state_estimators</depend>
  <depend>pairs_uav_autostart</depend>
  <depend>pairs_multirotor_simulator</depend>
  <depend>pairs_rviz_plugins</depend>
  <depend>pairs_uav_trajectory_generation</depend>
  <depend>pairs_uav_status</depend>
  <test_depend>pairs_uav_testing</test_depend>

  <depend>tmux</depend>
  <depend>tmuxinator</depend>
  <depend>catkin</depend>
  <depend>python3-catkin-tools</depend>
  <depend>moreutils</depend>

</package>
